### ISSUE TITLE
Button to Activate Voice-Over

### ISSUE THREAD

**Issue by CoryBrown-42** [RemakeWV/Coal-Mine-War#11]
The button will play an audio clip giving a brief description of the item and it's history.

**Comment by CoryBrown-42** [comment]
We need to add a button to the UI

**Comment by uglymunkeystudio** [comment]
Pause and play buttons added to project. Updated exhibit description UI for button spacing. No functionality added to play button yet.

**Comment by CoryBrown-42** [comment]
the functionality is in to play the sound and swap out the pause and play based on the duration of the voiceover. somewhere it isn't setting the sound to play so it's coming up null, I might need another set of eyes just to make sure I'm not missing something. 
the logic is in test widget, and I'm passing data to it from the world widget actor bp.

**Comment by CoryBrown-42** [comment]
fixed the above bug, need to work more on the pausing and playing functionality but will make a new card for it. closing for now
