### ISSUE TITLE
Character height buttons

### ISSUE THREAD

**Issue by CoryBrown-42** [RemakeWV/Coal-Mine-War#24]

**Comment by CoryBrown-42** [comment]
Double check and make sure this works in both desktop and VR.

**Comment by CoryBrown-42** [comment]
find a better formula for normalizing the player height

**Comment by CoryBrown-42** [comment]
Make buttons instead

**Comment by CoryBrown-42** [comment]
UI is there, just need to send events to the player to update the height from settings

**Comment by CoryBrown-42** [comment]
Game instance cast to each pawn and adjust height

**Comment by CoryBrown-42** [comment]
Working for desktop, will add to VR

**Comment by theRealDarkFact** [comment]
Implemented an options menu from the start that can use and modify the player height.

**Comment by CoryBrown-42** [comment]
We shouldn't need to use this character height in the menu, it'll end up being a 3D menu with a fixed camera, world menu.

I've added the changes needed to lower and raise the VR pawn and this is now implemented, could use testing.
