### ISSUE TITLE
Elevator

### ISSUE THREAD

**Issue by CoryBrown-42** [RemakeWV/Coal-Mine-War#26]

**Comment by CoryBrown-42** [comment]
Implemented super basic elevator. The interaction should be physically but also respond to players iInteractable - Activate interface call.

Think "I wanna press a button"

**Comment by CoryBrown-42** [comment]
Also haptic feedback.

**Comment by AdmiralOctavius** [comment]
Implemented a more complete elevator with door transitions and smooth up down movement. Needs more complete models and sounds but is functionally complete.

**Comment by CoryBrown-42** [comment]
Closing for now, we'll polish in future release.
